# Generated by Django 5.0.7 on 2024-07-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Txn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=200)),
                ("amount", models.FloatField()),
                ("memo", models.CharField(max_length=200)),
                ("post_date", models.DateTimeField(verbose_name="date posted")),
                ("txn_date", models.DateTimeField(verbose_name="date created")),
            ],
        ),
    ]
